# Generated by Django 3.2.21 on 2023-09-23 01:16

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('petApp', '0003_auto_20230923_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.CharField(max_length=18, validators=[django.core.validators.MinLengthValidator(16)])),
                ('event_place', models.CharField(max_length=80)),
                ('event_information', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 9, 23, 10, 16, 19, 302922))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2023, 9, 23, 10, 16, 19, 302922))),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petApp.petmodel')),
            ],
            options={
                'db_table': 'pet_comment',
            },
        ),
    ]
