# Generated by Django 3.2.21 on 2023-10-02 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petCommentApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petcommentmodel',
            name='event_time',
        ),
        migrations.AlterField(
            model_name='petcommentmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 8, 34, 0, 311785)),
        ),
        migrations.AlterField(
            model_name='petcommentmodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 8, 34, 0, 311785)),
        ),
    ]
