# Generated by Django 3.2.21 on 2023-10-02 23:37

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('petCommentApp', '0002_auto_20231003_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='petcommentmodel',
            name='event_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='petcommentmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 8, 37, 7, 993411)),
        ),
        migrations.AlterField(
            model_name='petcommentmodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 8, 37, 7, 993411)),
        ),
    ]
