# Generated by Django 3.2.21 on 2023-10-02 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petCommentApp', '0003_auto_20231003_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petcommentmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 8, 39, 40, 118806)),
        ),
        migrations.AlterField(
            model_name='petcommentmodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 8, 39, 40, 118806)),
        ),
    ]
