# Generated by Django 3.2.21 on 2023-10-03 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petCommentApp', '0005_auto_20231003_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petcommentmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 14, 17, 13, 130769)),
        ),
        migrations.AlterField(
            model_name='petcommentmodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 14, 17, 13, 130769)),
        ),
    ]
