# Generated by Django 3.2.21 on 2023-09-21 12:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petmodel',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ownerApp.owner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 21, 21, 10, 32, 894148)),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 21, 21, 10, 32, 894148)),
        ),
        migrations.AlterModelTable(
            name='petmodel',
            table='pet',
        ),
    ]
