# Generated by Django 3.2.21 on 2023-09-23 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petApp', '0002_auto_20230921_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 23, 10, 16, 19, 296377)),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='image',
            field=models.ImageField(upload_to='pet/'),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 23, 10, 16, 19, 296377)),
        ),
    ]
