# Generated by Django 3.2.21 on 2023-09-23 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petApp', '0003_auto_20230923_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petmodel',
            old_name='charmPoint',
            new_name='charm_point',
        ),
        migrations.RenameField(
            model_name='petmodel',
            old_name='postCord',
            new_name='post_cord',
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 24, 5, 56, 34, 511018)),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 24, 5, 56, 34, 511018)),
        ),
    ]
