# Generated by Django 3.2.21 on 2023-10-05 01:17

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petApp', '0005_auto_20231004_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 5, 10, 17, 40, 219804)),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='post_cord',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 5, 10, 17, 40, 219804)),
        ),
    ]
