# Generated by Django 3.2.21 on 2023-10-05 02:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petApp', '0006_auto_20231005_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 5, 11, 20, 5, 764804)),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='post_cord',
            field=models.IntegerField(max_length=7, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 5, 11, 20, 5, 764804)),
        ),
    ]
