# Generated by Django 3.2.21 on 2023-09-21 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={},
        ),
        migrations.AlterField(
            model_name='owner',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 21, 21, 10, 32, 892595)),
        ),
        migrations.AlterField(
            model_name='owner',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 21, 21, 10, 32, 892595)),
        ),
        migrations.AlterModelTable(
            name='owner',
            table='owner',
        ),
    ]
